import * as globalStyles from './globalStyles';
import {StyleSheet} from 'react-native';

export const theme = {
  backgroundColor: '#1F2937',
  calendarBackground: '#1F2937',
  textSectionTitleColor: '#b6c1cd',
  textSectionTitleDisabledColor: '#d9e1e8',
  selectedDayBackgroundColor: '#00adf5',
  selectedDayTextColor: '#ffffff',
  todayTextColor: '#00adf5',
  dayTextColor: 'white',
  textDisabledColor: '#d9e1e8',
  dotColor: '#00adf5',
  selectedDotColor: '#ffffff',
  disabledArrowColor: '#d9e1e8',
  monthTextColor: 'white',
  indicatorColor: 'blue',
  // textDayFontFamily: 'monospace',
  // textMonthFontFamily: 'monospace',
  // textDayHeaderFontFamily: 'monospace',
  textDayFontWeight: '300',
  textMonthFontWeight: 'bold',
  textDayHeaderFontWeight: '300',
  textDayFontSize: 16,
  textMonthFontSize: 16,
  textDayHeaderFontSize: 16,
  //   agendaDayTextColor: 'yellow',
  //   agendaDayNumColor: 'green',
  //   agendaTodayColor: 'red',
  //   agendaKnobColor: 'blue',
};
